### ISSUE TITLE
`require': no such file to load -- osx/foundation

### ISSUE THREAD

**Issue by jmccartie** [devstructure/doubledown#7]
When running, I get this error:

[doubledown] syncing baseline from remote
[doubledown] syncing local changes to remote

internal:lib/rubygems/custom_require:29:in 'require': no such file to load -- osx/foundation (LoadError)
from internal:lib/rubygems/custom_require:29:in 'require'
from /usr/local/bin/doubledown-fsevents:4:in `<main>'

Running:
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0]

**Comment by jmccartie** [comment]
problem with my install, not doubledown.  closing.

**Comment by rcrowley** [comment]
Smells like you're using RVM.  Am I right?

Maybe I should change the shebang line to `#!/usr/bin/ruby` to force it to use system Ruby (which has the `osx/foundation` file in its `$RUBYLIB`.

**Comment by jmccartie** [comment]
Dunno if I'm using RVM -- don't think I am.  :\

**Comment by rcrowley** [comment]
jmccartie, give 03899bbc3310737a673b63611315059670dd8e7d a try.  This really should have been the case anyway and will be in 0.0.3 (which is unscheduled at this point).

**Comment by jmccartie** [comment]
Cloned 0389, moved bin/\* to /usr/local/bin/    ran doubledown on my folders and get the same error. 

Ruby looks ok (irb too).  :\   

sorry to be the turd in the punch bowl.  i really don't expect help since it looks like I've got a setup issue, so i really appreciate the comments you've left.

**Comment by rcrowley** [comment]
Another potentially easy fix: do you have the OS X developer tools installed?  You can check by running `gcc -v`.

**Comment by jmccartie** [comment]
Yes

Using built-in specs.
Target: i686-apple-darwin10
Configured with: /var/tmp/gcc/gcc-5664~38/src/configure --disable-checking --enable-werror --prefix=/usr --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin10 --program-prefix=i686-apple-darwin10- --host=x86_64-apple-darwin10 --target=i686-apple-darwin10 --with-gxx-include-dir=/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Apple Inc. build 5664)

**Comment by rcrowley** [comment]
Damn, wrong again!  I'll keep thinking and let you know if I find any other potential culprits.

**Comment by jmccartie** [comment]
Dang -- thought you might be onto something ;)

I'll keep poking around and post if i get it fixed.

**Comment by jmccartie** [comment]
By running "export RUBYLIB=/usr/lib/ruby/1.8/" prior to doubledown, the error changes:

```
[doubledown] syncing local changes to remote
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- thread.so (LoadError)
from <internal:lib/rubygems/custom_require>:29:in `require'
from /usr/lib/ruby/1.8/thread.rb:5:in `<top (required)>'
from <internal:lib/rubygems/custom_require>:29:in `require'
from <internal:lib/rubygems/custom_require>:29:in `require'
from /usr/lib/ruby/1.8/rubygems.rb:9:in `<top (required)>'
from <internal:lib/rubygems/custom_require>:29:in `require'
from <internal:lib/rubygems/custom_require>:29:in `require'
from <internal:gem_prelude>:167:in `load_full_rubygems_library'
from <internal:gem_prelude>:217:in `try_activate'
from <internal:lib/rubygems/custom_require>:32:in `rescue in require'
from <internal:lib/rubygems/custom_require>:29:in `require'
from /usr/lib/ruby/1.8/osx/foundation.rb:8:in `<top (required)>'
from <internal:lib/rubygems/custom_require>:29:in `require'
from <internal:lib/rubygems/custom_require>:29:in `require'
from /usr/local/bin/doubledown-fsevents:4:in `<main>'
```

My buddy kmorey forked this repo and is doing some work on it. We're both trying to fix this error as we speak.

Cheers.
jon

**Comment by jmccartie** [comment]
Symlink fixed it for me:

/usr/bin/ruby -> ../../System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby

PS  I'm running Kmorey's fork:  http://github.com/kmorey/doubledown/commit/014d2a27a57e643de43e757dd75069adcccbce55

**Comment by rcrowley** [comment]
Curious, I've just looked at my Mac.  Lo and behold:

```
$
$ ls -l /usr/bin/ruby
lrwxr-xr-x  1 root  wheel  76 Feb 21  2008 /usr/bin/ruby -> ../../System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
$
```

So the next question seems to be why your Ruby was not set to that symlink originally?

**Comment by jmccartie** [comment]
I think I tried to install a new version of Ruby last year ... the wrong way.  :)

**Comment by timoxley** [comment]
Same issue here:

```
$ doubledown . timoxley@remote:/path/
Identity added: /Users/timoxley/.ssh/id_rsa (/Users/timoxley/.ssh/id_rsa)
Identity added: /Users/timoxley/.ssh/id_dsa (/Users/timoxley/.ssh/id_dsa)
# [doubledown] syncing baseline from remote
# [doubledown] syncing local changes to remote
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- osx/foundation (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /usr/local/bin/doubledown-fsevents:4:in `<main>'
```

Installed doubledown 0.0.2 with brew. 
No love. 
Am using rvm, issuing the following prior to using doubledown, makes works.

```
$ rvm use system
Now using system ruby.
$ doubledown . timoxley@remote:/path/
Identity added: /Users/timoxley/.ssh/id_rsa (/Users/timoxley/.ssh/id_rsa)
Identity added: /Users/timoxley/.ssh/id_dsa (/Users/timoxley/.ssh/id_dsa)
# [doubledown] syncing baseline from remote
# [doubledown] syncing local changes to remote
# [doubledown-fsevents] syncing /Users/timoxley/Projects/project changes to remote:/path/
```

Though I feel that if I'm installing this as a commandline utility via brew (instead of say, rubygems), I shouldn't have to do any such stuff.

Perhaps doubledown should do some dependency checking and spit out some kind of helpful messages or perhaps link directly to the system ruby at /usr/bin/ruby instead of whatever ruby the user has configured on their path.
